### ISSUE TITLE
Card/spread descriptions

### ISSUE THREAD

**Issue by mcorrell** [mcorrell/vis-tarot#2]
In tarot.js, we should have json for the cards and card slots that give descriptions of the cards, for tool tips or augmentation.

Ideally there would be an array of card objects with fields:
```
{
id: number // The value of the card, e.g. the fool is "0", the 10 of wands is "10"
name: string // The name of the card
suit?: string // The suit of the card, if minor arcana
description: string //Meanings or symbols present in the card, to be displayed as a tooltip.
}
```

**Comment by amcrisan** [comment]
major arcana portion addressed as part of update #14

**Comment by mcorrell** [comment]
Still todo here:
The card slots (@amcrisan I believe you had some opinions on this, but I can take a stab at some of them)
The minor arcana.

**Comment by amcrisan** [comment]
@mcnuttandrew and @mcorrell  : I can handle the spread descriptions. Might not get to it until tomorrow  or thursday because I have one more thing in my queue for today. Also, to consider here, is that we should do probably a stratified sampled sampling for card types and positions (i.e. major arcana should be oversampled, or exclusively sampled) for some positions in the spread relative to others. I'll also work that out and maybe hack out a spread specific sampling alg.

**Comment by mcorrell** [comment]
Okay. I'll put some initial placeholders there and then you can rewrite things as you want when you get around to it. Feel free to change names as well.

**Comment by amcrisan** [comment]
Working on this now ☝️

**Comment by amcrisan** [comment]
I think this is now done - handed with pull request #26 and #27
